name: women_safety
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #Design
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  carousel_slider: ^5.0.0
  webview_flutter: ^3.0.1
  curved_navigation_bar:
  page_transition:
  flutter_spinkit:

  #  Phone and url
  flutter_phone_direct_caller: ^2.1.1
  contacts_service: ^0.6.3
  fast_contacts:
  phone_state:


  url_launcher: ^6.1.5

  #  Toastification
  fluttertoast: ^8.0.9

  #  Maps
  google_maps_flutter:
  latlng:
  latlong2:
  geolocator:
  flutter_polyline_points:
  location:

  #Permission
  permission_handler: ^10.2.0
  #  Otp
  pinput:

  shared_preferences:
  #  web socket

  web_socket_channel:

  #    Firebase
  firebase_core: ^2.27.0
  firebase_messaging:
  firebase_analytics:
  cloud_firestore:
  firebase_storage:
  flutter_local_notifications:

  #  Splash Screen

  flutter_native_splash: ^2.3.10
  animated_splash_screen:

  #    Sms
  background_sms:

  #  Audio
  flutter_sound:
  audioplayers:
  porcupine_flutter:
  #Date format
  intl:

  #    Video Dependencies
  camera:
  video_player:
  dio:

  #    image
  image_picker: ^1.0.8

  #  Hardware devices
  volume_watcher:
  hardware_buttons_find_flutter:
  shake:

  #Design
  particles_flutter: ^1.0.1
  path: ^1.8.3
  smooth_page_indicator: ^1.2.1

  #sppech to text
  speech_to_text:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/womenSafety-app.png"
  min_sdk_android: 30


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/markers/


