// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1CyVPPFZkFjkfKyxBxyR3BLX6QuyEgbA',
    appId: '1:781714504024:android:9baf55bc37ad0da9af4d2d',
    messagingSenderId: '781714504024',
    projectId: 'safesarthi',
    storageBucket: 'safesarthi.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk9ie4a92wKjJLOB3mugXvp_X9f7gOWvg',
    appId: '1:781714504024:web:0350e404ff69f0d2af4d2d',
    messagingSenderId: '781714504024',
    projectId: 'safesarthi',
    authDomain: 'safesarthi.firebaseapp.com',
    storageBucket: 'safesarthi.firebasestorage.app',
    measurementId: 'G-GW3TY7Z5BM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG-2O-ht5BJR165AXnu3uXe7dq6jtPGYQ',
    appId: '1:781714504024:ios:5bb506438e3007e5af4d2d',
    messagingSenderId: '781714504024',
    projectId: 'safesarthi',
    storageBucket: 'safesarthi.firebasestorage.app',
    iosBundleId: 'com.example.womenSafety',
  );

}